/**
 * The plugin waits for each hook, so the snapshot is taken before the tool runs.
 * It never throws: a failed or slow hook only costs protection, never the tool call.
 * The end of a turn runs synchronously: \`opencode run\` exits right after \`session.idle\`,
 * before an async hook would have received its payload.
 */
export function opencodePluginSource(cli: string, marker: string): string {
  return `// ${marker} generated by \`turnback install opencode\`. Reinstall to update; uninstall removes it.
import { spawn, spawnSync } from 'node:child_process';

const CLI = ${JSON.stringify(cli)};
const ARGS = [CLI, 'hook', 'opencode'];
const TIMEOUT = 30_000;

function send(payload) {
  return new Promise(resolve => {
    const child = spawn('node', ARGS, { stdio: ['pipe', 'ignore', 'ignore'], windowsHide: true });
    const timer = setTimeout(() => child.kill(), TIMEOUT);
    const done = () => { clearTimeout(timer); resolve(); };
    child.on('error', done);
    child.on('close', done);
    child.stdin.on('error', () => {});
    child.stdin.end(JSON.stringify(payload));
  });
}

function sendSync(payload) {
  spawnSync('node', ARGS, { input: JSON.stringify(payload), stdio: ['pipe', 'ignore', 'ignore'], timeout: TIMEOUT, windowsHide: true });
}

export const Turnback = async ({ directory }) => {
  const payload = (hook_event_name, session_id, extra = {}) => ({ hook_event_name, session_id, cwd: directory, ...extra });
  const forward = (...args) => send(payload(...args));
  return {
    event: async ({ event }) => {
      if (event.type === 'session.created') await forward('session.created', event.properties.info?.id);
      else if (event.type === 'session.idle') sendSync(payload('session.idle', event.properties.sessionID));
    },
    'chat.message': async input => forward('chat.message', input.sessionID),
    'tool.execute.before': async (input, output) =>
      forward('tool.execute.before', input.sessionID, { tool_name: input.tool, tool_input: output.args }),
  };
};
`;
}
